### ISSUE TITLE
[UX] Settings Date Format - Date Popup Calendar Syntax

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/scheduler#10]
On the Scheduler `settings` page at `/admin/config/content/scheduler` - if the user selects the `Filed type` as `Date popup calendar` it can be quite tricky to pick the correct syntax as there is some discrepancy between which date / time formats are allowed when choosing between the Standard text field and `Date popup calendar` options.

For example:
The format `m/d/Y - g:ia` is allowed for the Standard text field type but not for the popup.

This is probably an issue with the Date Popup module in core rather than the Scheduler module.

**Comment by laryn** [comment]
I've converted the "date popup" to a "HTML datetime" field. I'm going to close this issue -- feel free to raise a new issue if you find a problem with that new implementation.
