### ISSUE TITLE
[UX] Settings - Link to Date Popup Config Page

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/scheduler#11]
On the Scheduler `settings` page at `/admin/config/content/scheduler` - the description for the `Date Popup minute increment` field includes a broken link to `Date Popup configuration page` at `/admin/config/date/date_popup`
Does Backdrop even have such a page?

**Comment by laryn** [comment]
Not that I know of... I will remove this option for now and can add it back later if appropriate when the date popup support is improved.
