### ISSUE TITLE
Date Format Conflicts

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/scheduler#12]
No matter what date format you enter into the `Date format` field on the Scheduler settings page at `/admin/config/content/scheduler`, the date popup calendar widget converts the date to` m/d/Y` and the expected format when trying to save the node is `Y-m-d H:m:s`.

**Comment by laryn** [comment]
I wonder if this is related to the core issue here:
https://github.com/backdrop/backdrop-issues/issues/1370

**Comment by laryn** [comment]
@Dinornis For the moment, can you set the Field Type to "Standard text field" rather than popup (for further testing purposes) on `admin/config/content/scheduler`? I may need some date help from others to get the popup working as expected.

**Comment by Dinornis** [comment]
Same problem with the standard text field, see #13

**Comment by laryn** [comment]
I believe this is fixed in dev. Once we have a little testing I will make a new release. Any chance you're able to test @Dinornis?
