### ISSUE TITLE
Save Node Expects Only Y-m-d H:m:s Date Format

### ISSUE THREAD

**Issue by Dinornis** [backdrop-contrib/scheduler#13]
No matter what date format user selects in the `Date format` field on the Scheduler settings page at `/admin/config/content/scheduler`, the expected format when trying to save the node is `Y-m-d H:m:s`.

![date-format-1](https://user-images.githubusercontent.com/24782789/30986426-e08e2502-a4ef-11e7-9965-e530de664b25.png)

---

![date-format-2](https://user-images.githubusercontent.com/24782789/30986454-f7e924f4-a4ef-11e7-8456-9b7e1a5c1e0c.png)

**Comment by laryn** [comment]
Duplicate of https://github.com/backdrop-contrib/scheduler/issues/12
