### ISSUE TITLE
Undefined language property

### ISSUE THREAD

**Issue by pgrayove-mcpl** [backdrop-contrib/scheduler#18]
`Notice: Undefined property: stdClass::$language in scheduler_tokens() (line 30 of /app/modules/contrib/scheduler/scheduler.tokens.inc).`

Looks like this:`function scheduler_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $language_code = isset($options['language']) ? $options['language']->language : NULL;
  $replacements = array();`

should be set to: `function scheduler_tokens($type, $tokens, array $data = array(), array $options = array()) {
  $language_code = isset($options['language']) ? $options['language']->langcode : NULL;
  $replacements = array();`

This error displays on all pages of an D7 site ported to Backdrop running php 7.4.

**Comment by laryn** [comment]
Thank you @pgrayove-mcpl !
